# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yandex_metrika}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrey \"Zed\" Zaikin"]
  s.date = %q{2009-10-12}
  s.description = %q{By default this gem will output Yandex.Metrika code for every page automagically, if it's configured correctly. This is done by adding:
Yandex::Metrika.counter_id = '123456'
to your `config/environment.rb`, inserting your own COUNTER_ID. This can be discovered by looking at the value of "new Ya.Metrika(123456)" in the Javascript code.}
  s.email = %q{zed.0xff@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CREDITS",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/yandex.rb",
     "lib/yandex/metrika.rb",
     "rails/init.rb",
     "test/test_helper.rb",
     "test/yandex_metrika_test.rb",
     "yandex_metrika.gemspec"
  ]
  s.homepage = %q{http://github.com/zed-0xff/yandex_metrika}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{[Rails] Easily enable Yandex.Metrika support in your Rails application.}
  s.test_files = [
    "test/yandex_metrika_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.3"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.3"])
    else
      s.add_dependency(%q<actionpack>, [">= 2.3.3"])
      s.add_dependency(%q<activesupport>, [">= 2.3.3"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 2.3.3"])
    s.add_dependency(%q<activesupport>, [">= 2.3.3"])
  end
end
