# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: yandex_metrika 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "yandex_metrika".freeze
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Andrey 'Zed' Zaikin".freeze]
  s.date = "2017-04-08"
  s.description = "[Rails] Easily enable Yandex.Metrika support in your Rails application.\n<br/><br/>\nBy default this gem will output Yandex.Metrika code for every page automagically, if it's configured correctly. This is done by adding: <br/>\nYandex::Metrika.counter_id = '123456' <br/>\nto your `config/environment.rb`, inserting your own COUNTER_ID. This can be discovered by looking at the value of \"new Ya.Metrika(123456)\" in the Javascript code.".freeze
  s.email = "zed.0xff@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "CREDITS",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/yandex.rb",
    "lib/yandex/metrika.rb",
    "lib/yandex_metrika.rb",
    "test/test_helper.rb",
    "test/yandex_metrika_test.rb",
    "yandex_metrika.gemspec"
  ]
  s.homepage = "http://github.com/zed-0xff/yandex_metrika".freeze
  s.rubyforge_project = "yandex-metrika".freeze
  s.rubygems_version = "2.6.8".freeze
  s.summary = "[Rails] Easily enable Yandex.Metrika support in your Rails application.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>.freeze, [">= 2.3.3"])
      s.add_runtime_dependency(%q<activesupport>.freeze, [">= 2.3.3"])
    else
      s.add_dependency(%q<actionpack>.freeze, [">= 2.3.3"])
      s.add_dependency(%q<activesupport>.freeze, [">= 2.3.3"])
    end
  else
    s.add_dependency(%q<actionpack>.freeze, [">= 2.3.3"])
    s.add_dependency(%q<activesupport>.freeze, [">= 2.3.3"])
  end
end

